export const data1 =[
    {
        id:1,
        name:"Trivandrum",
        Image:"https://www.statconsultants.com/projects/kims_tvm.jpg",
        desc:" Our services provided hospitals in Trivandrum. ",
        hosp1:" Ananthapuri hospital and reserach instritute",
        hosp2:"Cosmopotitan hospital",
        hosp3:"Sree Uthradam Thirunal hospital",
        hosp4:"Kerala Insitute of medical science(KIMS)",
        hosp5:"Providence Hospital",
        hosp6:"Gitanjali hospital",
        hosp7:"Sree krishna hospital",
        hosp8:"SRS Hospital",
        hosp9:"S K Hospital",
        hosp10:"Lords Hospital"
    },
    {
        id:2,
        name:"Kollam",
        Image:"https://content3.jdmagicbox.com/comp/kollam/d9/9999px474.x474.170906213652.q7d9/catalogue/sankars-hospital-chinnakada-kollam-private-hospitals-0oftcm3g1l.jpg",
        desc:"  Our services provided hospitals in Kollam.",
        hosp1:"Sabarigiri Multi National Hospital",
        hosp2:"Azezia Medical college Hospitral",
        hosp3:"Travancore Medicity Medical College Hospital",
        hosp4:"Government Medical college",
        hosp5:"N.S Memmorial Institute Of Medical Sciences",
        hosp6:"Sankar's Insitute Of Medical Sciences(SIMS)",
        hosp7:"Entrance of Govenrment District Hospital",
        hosp8:"Ashtamudi Hospital",
        hosp9:"Holy Cross Super Speciality Hospital ",
        hosp10:"Poyanil Hospital,Punalur"
    },
    {
        id:3,
        name:"Pathanmthitta",
        Image:"https://www.bcmch.org/medical_college_website/assets/img/hospital.jpg",
        desc:"Our services provided hospitals in Pathanamthitta.",
        hosp1:"Pushpagiri Hospital, Thiruvalla",
        hosp2:"Beliver's Church Medical College Hospital",
        hosp3:"Medical Mission Hospital Thiruvalla",
        hosp4:"Lifeline Hospital Adoor",
        hosp5:"Holly Cross Hospital Pathanamthitta",
        hosp6:"Medical TRust Hospital",
        hosp7:"Poyaniyil Hospital,Kozhencherry",
        hosp8:"MUthoot Hospital Kozhencherry",
        hosp9:"Fellowship Hospital, kumband",
        hosp10:"Medical Trust Hospital"
    },
    {
        id:4,
        name:"Alappuzha",
        Image:"https://keralahospitals.digital/wp-content/uploads/2021/12/Kerala-hospitals-19-1024x1024.png",
        desc:"Our services provided hospitals in Alappuzha.",
        hosp1:"T D Medical College",
        hosp2:"Sahrudaya Hospital",
        hosp3:"Sree Narayana Medical Mission Hospital",
        hosp4:"Sree Rama Krishna Hospital",
        hosp5:"Ebenezer Hospital",
        hosp6:"Philip Memorial hospital",
        hosp7:"St.Thomas hospital",
        hosp8:"Sagara Punnapra Co-Operative Hospital",
        hosp9:"Nicholas Hospital",
        hosp10:"Holly Cross Hospital"
    },
    {
        id:5,
        name:"Kottayam",
        Image:"https://keralahospitals.digital/wp-content/uploads/2021/12/Kerala-hospitals-32-1024x1024.png",
        desc:"Our services provided hospitals in Kottayam.",
        hosp1:"Caritas Hosspital",
        hosp2:"Mar Sleeva Medicity Cherpunkal",
        hosp3:"Bharath Hospital",
        hosp4:"Assisi Hospital",
        hosp5:"Marian Medical center",
        hosp6:"S H Medical Center Hospital",
        hosp7:"Mandiram Hospital",
        hosp8:"Mary Queen Mission Hospital",
        hosp9:"Matha Hospital",
        hosp10:"Mitera Hospital"
    },
    {
        id:6,
        name:"Idukki",
        Image:"https://keralahospitals.digital/wp-content/uploads/2022/01/Kerala-hospitals-74-1024x1024.png",
        desc:"Our services provided hospitals in Idukki.",
        hosp1:"CMS-Chazhikattu Hospital",
        hosp2:"St.Johns Hospital",
        hosp3:"Mundakayam Medical Trust Hospital",
        hosp4:"Holy family Hospital",
        hosp5:"Life Blooms Hospital",
        hosp6:"Bavasons Archana Hospital",
        hosp7:"High Range Hospital",
        hosp8:"Al-azhar Medical college hospital",
        hosp9:"Life Line Hospital",
        hosp10:"St.Johns Hospital"
    },
    {
        id:7,
        name:"Ernakulam",
        Image:"https://www.rajagirihospital.com/Userfiles/Poster/2bc5e43752c04d55904ea8db56579e96.jpg",
        desc:"Our services provided hospitals in Ernakulam.",
        hosp1:"Vps Lekeshore Hospital",
        hosp2:"Aster Medicity Hospital",
        hosp3:"Specialists Hospital",
        hosp4:"Rajagiri Hospital",
        hosp5:"Amrita Institute Of Medical Sciences",
        hosp6:"Medicaal Trust Hospital",
        hosp7:"Lisie Hospital",
        hosp8:"Ernakulam Medical Center",
        hosp9:"Welcare Hospital",
        hosp10:"KIMS Hospital"
    },
    {
        id:8,
        name:"Thrissur",
        Image:"https://content.jdmagicbox.com/comp/malda/t8/9999p3512.3512.221017124525.v2t8/catalogue/-39wbkeiu6w.jpg",
        desc:"Our services provided hospitals in Thrissur.",
        hosp1:"Government Hospital",
        hosp2:"Jubilee Mission Medical College ",
        hosp3:"Kasim Memorial Hospital",
        hosp4:"Modern Hospital",
        hosp5:"Medicare Hospital",
        hosp6:"Westfort Hospital",
        hosp7:"Amala Cancer Hospital And Research Center",
        hosp8:"Mother Hospital",
        hosp9:"Unity Hospital",
        hosp10:"Ansar Hospital"
    },
    {
        id:9,
        name:"Palakkad",
        Image:"https://content.jdmagicbox.com/comp/palakkad/n9/9999px491.x491.141028230040.m6n9/catalogue/crescent-hospital-alathur-palakkad-palakkad-private-hospitals-9kty2mx.jpg",
        desc:"Our services provided hospitals in Palakkad.",
        hosp1:"Sai Hospital",
        hosp2:"Rishi Hospital",
        hosp3:"District co-operative Hospital",
        hosp4:"Lakshmi Hospital,Palakkad",
        hosp5:"Thangam Hospital of PMRC",
        hosp6:"NIMS Welcare Hospital",
        hosp7:"New Alma Hospital",
        hosp8:"Life Line Hospital",
        hosp9:"Karuna Medical College",
        hosp10:"Swami Vivekanada Hospital"
    },
    {
        id:10,
        name:"Malappuram",
        Image:"https://www.vaidam.com/sites/default/files/hospitals/kovai_medical_center_and_hospital.jpg",
        desc:"Our services provided hospitals in Malappuram",
        hosp1:"Almas Hospital",
        hosp2:"KIMS health Hospital",
        hosp3:"MB Hospital",
        hosp4:"Nadakkavil Hospital",
        hosp5:"PMSA Memorial Malappuram District Hospital",
        hosp6:"NIMS Hospital",
        hosp7:"Edappal Hospital",
        hosp8:"Korambayil Hospital",
        hosp9:"Aster MIMS",
        hosp10:"PKM Hospital"
    },
    {
        id:11,
        name:"Kozhikode",
        Image:"https://www.gomyhealth.com/wp-content/uploads/2018/11/aster-mims-calicut.jpg",
        desc:"Our services provided hospitals in Kozhikode.",
        hosp1:"Aster MIMS",
        hosp2:"Baby Memorial Hospital",
        hosp3:"Matria Hospital",
        hosp4:"Fathima Hospital",
        hosp5:"Ascent Hospital",
        hosp6:"Meitra Hospital",
        hosp7:"Lisa Hospital",
        hosp8:"Lisa Hospital",
        hosp9:"Starcare Hospital",
        hosp10:"National Hospital"
    },
    {
        id:12,
        name:"Wayanad",
        Image:"https://sys.mediflam.com/OfflineUploads/HospitalImage/ASTER_SPECIALITY_WAYANAD.JPG",
        desc:"Our services provided hospitals in Wayanad.",
        hosp1:"Aster Wayanad",
        hosp2:"IQRAA Hospital",
        hosp3:"Fatima Mata Mission Hospital",
        hosp4:"Swami Vivekanda Medical Mission",
        hosp5:"St.Martins Hospital",
        hosp6:"Assumption Hospital",
        hosp7:"Vinayaka Hospital",
        hosp8:"Assumption Hospital",
        hosp9:"DM Wayanad Insitute of Medical Science ",
        hosp10:""
    },
    {
        id:13,
        name:"Kannur",
        Image:"https://keralahospitals.digital/wp-content/uploads/2022/03/Copy-of-Kerala-hospitals-1-1024x1024.png",
        desc:"Our services provided hospitals in Kannur.",
        hosp1:"Lourde Hospital",
        hosp2:"Anamaya Medical Insitute",
        hosp3:"Life Line Hospital",
        hosp4:"Fathima Hospital",
        hosp5:"Dhanalakshmi Hospital",
        hosp6:"Koyil Hospital ",
        hosp7:"Fathima Hospital",
        hosp8:"AKG Memorial Co-operative Hospital",
        hosp9:"KIMST Hospital",
        hosp10:"Madhavrao Scindia Hospital"
    },
    {
        id:14,
        name:"Kasargod",
        Image:"https://content.jdmagicbox.com/comp/kasaragod/x3/9999p4994.4994.180622180837.g9x3/catalogue/k-a-h-m-hospital-chervathur-kasaragod-general-physician-doctors-hnw7tq5hwz.jpg",
        desc:"Our services provided hospitals in Kasargod.",
        hosp1:"K A H M A Hospital",
        hosp2:"Cee Yam Hospital Vadakara",
        hosp3:"Shashirekha Multispeciality Hospital",
        hosp4:"Manzoor Hospital",
        hosp5:"Malabar Hospital",
        hosp6:"Life Line Hospital",
        hosp7:"KIMS Sunrise Hospital",
        hosp8:"Government District Hospital",
        hosp9:"Krishna Hospital",
        hosp10:"Thejaswini Co-Operative Hospital"
    },
    


]